# First introduction in Pandas

In [2]:
import pandas as pd # importing panda library with pd nickname

In [15]:
chicago_crimes = pd.read_csv("data.csv") # load data in my computer offline, downloaded in https://data.cityofchicago.org/api/views/9hwr-2zxp/rows.csv?accessType=DOWNLOAD&bom=true&format=true

In [17]:
chicago_crimes.head() # the first 5 rows of data set

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13032945,JG212426,10/23/2022 12:00:00 PM,006XX W IRVING PARK RD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,46.0,6,26,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
1,12713141,JF259485,05/29/2022 12:00:00 AM,014XX S MUSEUM CAMPUS DR,0870,THEFT,POCKET-PICKING,SPORTS ARENA / STADIUM,False,False,...,4.0,33,06,NaN,NaN,2022,06/05/2022 04:48:59 PM,NaN,NaN,NaN
2,13032436,JG211735,04/20/2022 12:01:00 AM,039XX S CALIFORNIA AVE,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,POLICE FACILITY / VEHICLE PARKING LOT,False,False,...,12.0,58,17,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
3,13032916,JG212285,12/14/2022 03:35:00 PM,007XX E 40TH ST,0890,THEFT,FROM BUILDING,SCHOOL - PRIVATE BUILDING,False,False,...,4.0,38,06,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
4,12871591,JF449106,10/17/2022 05:24:00 PM,022XX N KEELER AVE,0820,THEFT,$500 AND UNDER,RESIDENCE - PORCH / HALLWAY,False,False,...,35.0,20,06,NaN,NaN,2022,10/26/2022 04:52:31 PM,NaN,NaN,NaN

In [18]:
chicago_crimes.dtypes # all types of data from data set

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                  int64
Ward                    float64
Community Area            int64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [19]:
chicago_crimes.tail() # the last 5 rows of data set

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
238658,13130030,JG328516,06/17/2022 12:01:00 AM,004XX S LOTUS AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,29.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238659,13128041,JG326305,12/01/2022 12:00:00 AM,049XX W WEST END AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,...,28.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238660,13128260,JG325445,10/02/2022 04:15:00 PM,082XX S DREXEL AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,8.0,44,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238661,13129895,JG328258,01/01/2022 12:01:00 AM,008XX W BUENA AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,46.0,3,26,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238662,13129286,JG326911,12/22/2022 12:00:00 PM,030XX N SHEFFIELD AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,44.0,6,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN

In [22]:
chicago_crimes.info() # information from data set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238663 entries, 0 to 238662
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    238663 non-null  int64
 1   Case Number           238663 non-null  object
 2   Date                  238663 non-null  object
 3   Block                 238663 non-null  object
 4   IUCR                  238663 non-null  object
 5   Primary Type          238663 non-null  object
 6   Description           238663 non-null  object
 7   Location Description  237846 non-null  object
 8   Arrest                238663 non-null  bool
 9   Domestic              238663 non-null  bool
 10  Beat                  238663 non-null  int64
 11  District              238663 non-null  int64
 12  Ward                  238653 non-null  float64
 13  Community Area        238663 non-null  int64
 14  FBI Code              238663 non-null  object
 15  X Coordinate          233092 non-null  float64
 16  Y Coordinate          233092 non-null  float64
 17  Year                  238663 non-null  int64
 18  Updated On            238663 non-null  object
 19  Latitude              233092 non-null  float64
 20  Longitude             233092 non-null  float64
 21  Location              233092 non-null  object
dtypes: bool(2), float64(5), int64(5), object(10)
memory usage: 36.9+ MB

In [24]:
chicago_crimes.isna() # verify if exist null informations in data set

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238658,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,True,True
238659,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,True,True
238660,False,False,False,False,False,False,False,True,False,False,...,False,False,False,True,True,False,False,True,True,True
238661,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,True,True
238662,False,False,False,False,False,False,False,True,False,False,...,False,False,False,True,True,False,False,True,True,True

In [25]:
chicago_crimes.isna().sum() # shows the sum of empty values in each column

ID                         0
Case Number                0
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description     817
Arrest                     0
Domestic                   0
Beat                       0
District                   0
Ward                      10
Community Area             0
FBI Code                   0
X Coordinate            5571
Y Coordinate            5571
Year                       0
Updated On                 0
Latitude                5571
Longitude               5571
Location                5571
dtype: int64

In [30]:
chicago_crimes.loc[100] # 101 th row of data set (remember zero is the first line)

ID                                    13034577
Case Number                           JG214408
Date                    09/01/2022 06:00:00 PM
Block                      007XX W SHERIDAN RD
IUCR                                      0820
Primary Type                             THEFT
Description                     $500 AND UNDER
Location Description                 APARTMENT
Arrest                                   False
Domestic                                 False
Beat                                      1925
District                                    19
Ward                                      46.0
Community Area                               6
FBI Code                                    06
X Coordinate                               NaN
Y Coordinate                               NaN
Year                                      2022
Updated On              04/08/2023 05:06:00 PM
Latitude                                   NaN
Longitude                                  NaN
Location                                   NaN
Name: 100, dtype: object

In [31]:
chicago_crimes.loc[10:20] # index rows 10 to 20 of data set (closed range)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
10,12863160,JF439075,10/18/2022 12:00:00 AM,005XX S CENTRAL AVE,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,SIDEWALK,False,False,...,29.0,25,17,1139141.0,1897035.0,2022,07/06/2023 04:46:09 PM,41.873578,-87.764614,"(41.873578134, -87.764614167)"
11,12886511,JF467255,11/07/2022 12:00:00 AM,065XX S MOZART ST,1750,OFFENSE INVOLVING CHILDREN,CHILD ABUSE,RESIDENCE,False,False,...,15.0,66,08B,1158504.0,1861158.0,2022,07/06/2023 04:46:09 PM,41.774753,-87.694502,"(41.774753227, -87.694501757)"
12,12901029,JF484488,11/22/2022 10:01:00 PM,0000X W 114TH PL,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,RESIDENCE,True,False,...,9.0,49,15,1177990.0,1829046.0,2022,07/06/2023 04:46:09 PM,41.686214,-87.624039,"(41.686214418, -87.624039314)"
13,12907258,JF489781,11/27/2022 07:15:00 PM,061XX S CAMPBELL AVE,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,VEHICLE - COMMERCIAL,False,False,...,16.0,66,03,1160756.0,1863907.0,2022,07/06/2023 04:46:09 PM,41.782251,-87.686170,"(41.782250663, -87.686170377)"
14,12910781,JF496081,12/02/2022 10:06:00 PM,055XX S THROOP ST,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,ALLEY,False,False,...,16.0,67,15,1168605.0,1867976.0,2022,07/06/2023 04:46:09 PM,41.793251,-87.657276,"(41.793250772, -87.65727644)"
15,12929044,JF517984,12/20/2022 08:45:00 PM,083XX S OGLESBY AVE,0325,ROBBERY,VEHICULAR HIJACKING,VEHICLE NON-COMMERCIAL,False,False,...,7.0,46,03,1193289.0,1850362.0,2022,07/06/2023 04:46:09 PM,41.744348,-87.567339,"(41.744348335, -87.567339144)"
16,13129968,JG328444,05/25/2022 12:00:00 AM,066XX N ASHLAND AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,49.0,1,11,NaN,NaN,2022,07/06/2023 04:46:09 PM,NaN,NaN,NaN
17,13130214,JG328707,09/01/2022 12:00:00 AM,0000X W DIVISION ST,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,2.0,8,07,NaN,NaN,2022,07/06/2023 04:48:39 PM,NaN,NaN,NaN
18,13130521,JG328878,07/05/2022 12:00:00 AM,061XX S ROCKWELL ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,...,16.0,66,17,NaN,NaN,2022,07/06/2023 04:48:39 PM,NaN,NaN,NaN
19,12869081,JF445514,10/20/2022 10:05:00 AM,002XX E CHICAGO AVE,0810,THEFT,OVER $500,SIDEWALK,False,False,...,2.0,8,06,NaN,NaN,2022,10/27/2022 04:47:08 PM,NaN,NaN,NaN
20,13130275,JG328904,10/31/2022 10:21:00 PM,012XX N WOLCOTT AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,APARTMENT,False,False,...,1.0,24,11,NaN,NaN,2022,07/06/2023 04:48:39 PM,NaN,NaN,NaN

In [32]:
chicago_crimes['Description'] # informations of column "Description" on data set

0              HARASSMENT BY ELECTRONIC MEANS
1                              POCKET-PICKING
2                           CHILD PORNOGRAPHY
3                               FROM BUILDING
4                              $500 AND UNDER
                         ...
238658    FINANCIAL IDENTITY THEFT OVER $ 300
238659    FINANCIAL IDENTITY THEFT OVER $ 300
238660    FINANCIAL IDENTITY THEFT OVER $ 300
238661                HARASSMENT BY TELEPHONE
238662    FINANCIAL IDENTITY THEFT OVER $ 300
Name: Description, Length: 238663, dtype: object

In [33]:
chicago_crimes[['Description', 'Location Description']] # info of 2 column on data set (inner brackets required)

,Description,Location Description
0,HARASSMENT BY ELECTRONIC MEANS,APARTMENT
1,POCKET-PICKING,SPORTS ARENA / STADIUM
2,CHILD PORNOGRAPHY,POLICE FACILITY / VEHICLE PARKING LOT
3,FROM BUILDING,SCHOOL - PRIVATE BUILDING
4,$500 AND UNDER,RESIDENCE - PORCH / HALLWAY
...,...,...
238658,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT
238659,FINANCIAL IDENTITY THEFT OVER $ 300,STREET
238660,FINANCIAL IDENTITY THEFT OVER $ 300,NaN
238661,HARASSMENT BY TELEPHONE,APARTMENT
238662,FINANCIAL IDENTITY THEFT OVER $ 300,NaN

In [35]:
chicago_crimes[['Location Description']] # info of one colomn in rows (brackets and their use in python)

                         Location Description
0                                   APARTMENT
1                      SPORTS ARENA / STADIUM
2       POLICE FACILITY / VEHICLE PARKING LOT
3                   SCHOOL - PRIVATE BUILDING
4                 RESIDENCE - PORCH / HALLWAY
...                                       ...
238658                              APARTMENT
238659                                 STREET
238660                                    NaN
238661                              APARTMENT
238662                                    NaN

[238663 rows x 1 columns]

In [41]:
chicago_crimes['Primary Type'].loc[10] # specifically 11th row with the column "Primary Type"

'OFFENSE INVOLVING CHILDREN'

In [46]:
chicago_crimes[['Primary Type', 'Date']].loc[10] # 11th row with the columns "Primary Type" and "Date"

Primary Type    OFFENSE INVOLVING CHILDREN
Date                10/18/2022 12:00:00 AM
Name: 10, dtype: object

In [48]:
chicago_crimes[['Primary Type', 'Date']].loc[10:15] # index 10 to 15 of rows with the columns "Primary Type" and "Date"

                  Primary Type                    Date
10  OFFENSE INVOLVING CHILDREN  10/18/2022 12:00:00 AM
11  OFFENSE INVOLVING CHILDREN  11/07/2022 12:00:00 AM
12           WEAPONS VIOLATION  11/22/2022 10:01:00 PM
13                     ROBBERY  11/27/2022 07:15:00 PM
14           WEAPONS VIOLATION  12/02/2022 10:06:00 PM
15                     ROBBERY  12/20/2022 08:45:00 PM

In [55]:
chicago_crimes['Ward'].isna().sum() # number of null informations in column "Ward"

10

In [57]:
chicago_crimes[['Ward']].isna().sum() # same result above, now with square brackets

Ward    10
dtype: int64

In [60]:
chicago_crimes_subset = chicago_crimes[['Date', 'FBI Code', 'Description']] # create an sub data set with 3 colunm
chicago_crimes_subset # print

                          Date FBI Code                          Description
0       10/23/2022 12:00:00 PM       26       HARASSMENT BY ELECTRONIC MEANS
1       05/29/2022 12:00:00 AM       06                       POCKET-PICKING
2       04/20/2022 12:01:00 AM       17                    CHILD PORNOGRAPHY
3       12/14/2022 03:35:00 PM       06                        FROM BUILDING
4       10/17/2022 05:24:00 PM       06                       $500 AND UNDER
...                        ...      ...                                  ...
238658  06/17/2022 12:01:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238659  12/01/2022 12:00:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238660  10/02/2022 04:15:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238661  01/01/2022 12:01:00 AM       26              HARASSMENT BY TELEPHONE
238662  12/22/2022 12:00:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300

[238663 rows x 3 columns]

In [61]:
chicago_crimes_subset.drop(2) # show the dataset without the 3th row (only show, don't deleted)

                          Date FBI Code                          Description
0       10/23/2022 12:00:00 PM       26       HARASSMENT BY ELECTRONIC MEANS
1       05/29/2022 12:00:00 AM       06                       POCKET-PICKING
3       12/14/2022 03:35:00 PM       06                        FROM BUILDING
4       10/17/2022 05:24:00 PM       06                       $500 AND UNDER
5       01/24/2022 05:30:00 PM       07                           AUTOMOBILE
...                        ...      ...                                  ...
238658  06/17/2022 12:01:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238659  12/01/2022 12:00:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238660  10/02/2022 04:15:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238661  01/01/2022 12:01:00 AM       26              HARASSMENT BY TELEPHONE
238662  12/22/2022 12:00:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300

[238662 rows x 3 columns]

In [65]:
chicago_crimes_subset = chicago_crimes[['Date', 'FBI Code', 'Description']].drop(2) # create subset without row 3th
chicago_crimes_subset

                          Date FBI Code                          Description
0       10/23/2022 12:00:00 PM       26       HARASSMENT BY ELECTRONIC MEANS
1       05/29/2022 12:00:00 AM       06                       POCKET-PICKING
3       12/14/2022 03:35:00 PM       06                        FROM BUILDING
4       10/17/2022 05:24:00 PM       06                       $500 AND UNDER
5       01/24/2022 05:30:00 PM       07                           AUTOMOBILE
...                        ...      ...                                  ...
238658  06/17/2022 12:01:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238659  12/01/2022 12:00:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238660  10/02/2022 04:15:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238661  01/01/2022 12:01:00 AM       26              HARASSMENT BY TELEPHONE
238662  12/22/2022 12:00:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300

[238662 rows x 3 columns]

In [71]:
chicago_crimes_subset.drop(4, inplace=True) # now it definitely removes the 5th row of the data set
chicago_crimes_subset

                          Date FBI Code                          Description
0       10/23/2022 12:00:00 PM       26       HARASSMENT BY ELECTRONIC MEANS
1       05/29/2022 12:00:00 AM       06                       POCKET-PICKING
3       12/14/2022 03:35:00 PM       06                        FROM BUILDING
5       01/24/2022 05:30:00 PM       07                           AUTOMOBILE
6       07/10/2022 08:00:00 PM       05                       FORCIBLE ENTRY
...                        ...      ...                                  ...
238658  06/17/2022 12:01:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238659  12/01/2022 12:00:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238660  10/02/2022 04:15:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238661  01/01/2022 12:01:00 AM       26              HARASSMENT BY TELEPHONE
238662  12/22/2022 12:00:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300

[238661 rows x 3 columns]

In [77]:
chicago_crimes_subset.drop([0,3]) # remove (olny view) rows of 1th and 4th

                          Date FBI Code                          Description
1       05/29/2022 12:00:00 AM       06                       POCKET-PICKING
5       01/24/2022 05:30:00 PM       07                           AUTOMOBILE
6       07/10/2022 08:00:00 PM       05                       FORCIBLE ENTRY
7       07/23/2022 04:00:00 PM      08B              DOMESTIC BATTERY SIMPLE
8       07/29/2022 03:09:00 AM      04A  AGGRAVATED POLICE OFFICER - HANDGUN
...                        ...      ...                                  ...
238658  06/17/2022 12:01:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238659  12/01/2022 12:00:00 AM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238660  10/02/2022 04:15:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300
238661  01/01/2022 12:01:00 AM       26              HARASSMENT BY TELEPHONE
238662  12/22/2022 12:00:00 PM       11  FINANCIAL IDENTITY THEFT OVER $ 300

[238659 rows x 3 columns]

In [82]:
chicago_crimes_subset.drop(columns='Date') # remove (only view) column "Date" from sub set data

       FBI Code                          Description
0            26       HARASSMENT BY ELECTRONIC MEANS
1            06                       POCKET-PICKING
3            06                        FROM BUILDING
5            07                           AUTOMOBILE
6            05                       FORCIBLE ENTRY
...         ...                                  ...
238658       11  FINANCIAL IDENTITY THEFT OVER $ 300
238659       11  FINANCIAL IDENTITY THEFT OVER $ 300
238660       11  FINANCIAL IDENTITY THEFT OVER $ 300
238661       26              HARASSMENT BY TELEPHONE
238662       11  FINANCIAL IDENTITY THEFT OVER $ 300

[238661 rows x 2 columns]

In [83]:
chicago_crimes_subset.drop(columns=['Date', 'FBI Code']) # remove (only view) columns "Date" and "FBI Code" from sub set data

                                Description
0            HARASSMENT BY ELECTRONIC MEANS
1                            POCKET-PICKING
3                             FROM BUILDING
5                                AUTOMOBILE
6                            FORCIBLE ENTRY
...                                     ...
238658  FINANCIAL IDENTITY THEFT OVER $ 300
238659  FINANCIAL IDENTITY THEFT OVER $ 300
238660  FINANCIAL IDENTITY THEFT OVER $ 300
238661              HARASSMENT BY TELEPHONE
238662  FINANCIAL IDENTITY THEFT OVER $ 300

[238661 rows x 1 columns]

In [87]:
chicago_crimes[chicago_crimes['Location Description'] == 'APARTMENT'] # all rows where "Location Description" is "APARTMENT"

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13032945,JG212426,10/23/2022 12:00:00 PM,006XX W IRVING PARK RD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,46.0,6,26,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
6,12757467,JF313006,07/10/2022 08:00:00 PM,007XX W 54TH PL,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,16.0,61,05,1172394.0,1868734.0,2022,07/06/2023 04:46:09 PM,41.795248,-87.643360,"(41.7952482, -87.643360273)"
9,12803695,JF367998,08/23/2022 10:29:00 PM,055XX S PRAIRIE AVE,041A,BATTERY,AGGRAVATED - HANDGUN,APARTMENT,True,True,...,20.0,40,04B,1178988.0,1868183.0,2022,07/06/2023 04:46:09 PM,41.793588,-87.619197,"(41.793588428, -87.619196923)"
16,13129968,JG328444,05/25/2022 12:00:00 AM,066XX N ASHLAND AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,49.0,1,11,NaN,NaN,2022,07/06/2023 04:46:09 PM,NaN,NaN,NaN
18,13130521,JG328878,07/05/2022 12:00:00 AM,061XX S ROCKWELL ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,...,16.0,66,17,NaN,NaN,2022,07/06/2023 04:48:39 PM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238626,27261,JF505836,12/16/2022 09:00:00 PM,042XX W 31ST ST,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,False,...,22.0,30,01A,1148731.0,1883705.0,2022,12/23/2022 03:48:06 PM,41.836819,-87.729748,"(41.836819184, -87.729748064)"
238641,27276,JF225079,05/03/2022 04:00:00 AM,034XX W SUNNYSIDE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,False,...,35.0,14,01A,1152427.0,1929689.0,2022,01/01/2023 03:49:23 PM,41.962932,-87.714970,"(41.962931649, -87.714969631)"
238647,27357,JF167335,04/05/2022 04:10:00 AM,060XX N KENMORE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,False,...,48.0,77,01A,1168152.0,1940164.0,2022,02/25/2023 03:44:55 PM,41.991349,-87.656851,"(41.991349382, -87.656850554)"
238658,13130030,JG328516,06/17/2022 12:01:00 AM,004XX S LOTUS AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,29.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238661,13129895,JG328258,01/01/2022 12:01:00 AM,008XX W BUENA AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,46.0,3,26,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN

In [88]:
chicago_crimes['Location Description'] == 'APARTMENT' # inner command above (boolean)

0          True
1         False
2         False
3         False
4         False
          ...
238658     True
238659    False
238660    False
238661     True
238662    False
Name: Location Description, Length: 238663, dtype: bool

In [95]:
# condition AND => '&', OR => '|' (parentheses are required)
chicago_crimes[(chicago_crimes['Location Description'] == 'APARTMENT') & (chicago_crimes['Ward'] > 15.0)]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13032945,JG212426,10/23/2022 12:00:00 PM,006XX W IRVING PARK RD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,46.0,6,26,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
6,12757467,JF313006,07/10/2022 08:00:00 PM,007XX W 54TH PL,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,16.0,61,05,1172394.0,1868734.0,2022,07/06/2023 04:46:09 PM,41.795248,-87.643360,"(41.7952482, -87.643360273)"
9,12803695,JF367998,08/23/2022 10:29:00 PM,055XX S PRAIRIE AVE,041A,BATTERY,AGGRAVATED - HANDGUN,APARTMENT,True,True,...,20.0,40,04B,1178988.0,1868183.0,2022,07/06/2023 04:46:09 PM,41.793588,-87.619197,"(41.793588428, -87.619196923)"
16,13129968,JG328444,05/25/2022 12:00:00 AM,066XX N ASHLAND AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,49.0,1,11,NaN,NaN,2022,07/06/2023 04:46:09 PM,NaN,NaN,NaN
18,13130521,JG328878,07/05/2022 12:00:00 AM,061XX S ROCKWELL ST,1752,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,APARTMENT,False,True,...,16.0,66,17,NaN,NaN,2022,07/06/2023 04:48:39 PM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238626,27261,JF505836,12/16/2022 09:00:00 PM,042XX W 31ST ST,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,False,...,22.0,30,01A,1148731.0,1883705.0,2022,12/23/2022 03:48:06 PM,41.836819,-87.729748,"(41.836819184, -87.729748064)"
238641,27276,JF225079,05/03/2022 04:00:00 AM,034XX W SUNNYSIDE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,False,...,35.0,14,01A,1152427.0,1929689.0,2022,01/01/2023 03:49:23 PM,41.962932,-87.714970,"(41.962931649, -87.714969631)"
238647,27357,JF167335,04/05/2022 04:10:00 AM,060XX N KENMORE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,False,...,48.0,77,01A,1168152.0,1940164.0,2022,02/25/2023 03:44:55 PM,41.991349,-87.656851,"(41.991349382, -87.656850554)"
238658,13130030,JG328516,06/17/2022 12:01:00 AM,004XX S LOTUS AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,29.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238661,13129895,JG328258,01/01/2022 12:01:00 AM,008XX W BUENA AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,46.0,3,26,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN

In [96]:
# not equal '!=' operator and OR condition
chicago_crimes[(chicago_crimes['Location Description'] != 'APARTMENT') | (chicago_crimes['Ward'] > 15.0)]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13032945,JG212426,10/23/2022 12:00:00 PM,006XX W IRVING PARK RD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,46.0,6,26,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
1,12713141,JF259485,05/29/2022 12:00:00 AM,014XX S MUSEUM CAMPUS DR,0870,THEFT,POCKET-PICKING,SPORTS ARENA / STADIUM,False,False,...,4.0,33,06,NaN,NaN,2022,06/05/2022 04:48:59 PM,NaN,NaN,NaN
2,13032436,JG211735,04/20/2022 12:01:00 AM,039XX S CALIFORNIA AVE,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,POLICE FACILITY / VEHICLE PARKING LOT,False,False,...,12.0,58,17,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
3,13032916,JG212285,12/14/2022 03:35:00 PM,007XX E 40TH ST,0890,THEFT,FROM BUILDING,SCHOOL - PRIVATE BUILDING,False,False,...,4.0,38,06,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
4,12871591,JF449106,10/17/2022 05:24:00 PM,022XX N KEELER AVE,0820,THEFT,$500 AND UNDER,RESIDENCE - PORCH / HALLWAY,False,False,...,35.0,20,06,NaN,NaN,2022,10/26/2022 04:52:31 PM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238658,13130030,JG328516,06/17/2022 12:01:00 AM,004XX S LOTUS AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,29.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238659,13128041,JG326305,12/01/2022 12:00:00 AM,049XX W WEST END AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,...,28.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238660,13128260,JG325445,10/02/2022 04:15:00 PM,082XX S DREXEL AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,8.0,44,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238661,13129895,JG328258,01/01/2022 12:01:00 AM,008XX W BUENA AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,46.0,3,26,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238662,13129286,JG326911,12/22/2022 12:00:00 PM,030XX N SHEFFIELD AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,44.0,6,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN

In [100]:
# show "Location Description" is 'RESIDENCE' OR 'APARTMENT' OR 'STREET'
chicago_crimes[(chicago_crimes['Location Description'] == 'RESIDENCE') | (chicago_crimes['Location Description'] == 'APARTMENT') | (chicago_crimes['Location Description'] == 'STREET')]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13032945,JG212426,10/23/2022 12:00:00 PM,006XX W IRVING PARK RD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,46.0,6,26,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
5,12600669,JF122951,01/24/2022 05:30:00 PM,018XX W GRAND AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,36.0,24,07,1164069.0,1903522.0,2022,07/06/2023 04:46:09 PM,41.890889,-87.672907,"(41.890889291, -87.672907259)"
6,12757467,JF313006,07/10/2022 08:00:00 PM,007XX W 54TH PL,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,16.0,61,05,1172394.0,1868734.0,2022,07/06/2023 04:46:09 PM,41.795248,-87.643360,"(41.7952482, -87.643360273)"
7,12770469,JF328862,07/23/2022 04:00:00 PM,069XX W 64TH PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,True,...,13.0,64,08B,1131307.0,1860969.0,2022,07/06/2023 04:46:09 PM,41.774746,-87.794208,"(41.774745709, -87.794208216)"
8,12776417,JF335627,07/29/2022 03:09:00 AM,052XX N NAGLE AVE,0550,ASSAULT,AGGRAVATED POLICE OFFICER - HANDGUN,STREET,False,False,...,41.0,10,04A,1132572.0,1934567.0,2022,07/06/2023 04:46:09 PM,41.976687,-87.787856,"(41.976687342, -87.787856137)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238654,12678162,JF216753,04/23/2022 03:56:00 AM,047XX S LOOMIS BLVD,041A,BATTERY,AGGRAVATED - HANDGUN,STREET,False,False,...,20.0,61,04B,1167798.0,1873280.0,2022,01/03/2023 03:46:28 PM,41.807823,-87.660083,"(41.807822931, -87.660083294)"
238655,13129089,JG327504,09/27/2022 12:00:00 AM,059XX N HERMITAGE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,False,...,40.0,77,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238658,13130030,JG328516,06/17/2022 12:01:00 AM,004XX S LOTUS AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,29.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238659,13128041,JG326305,12/01/2022 12:00:00 AM,049XX W WEST END AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,...,28.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238661,13129895,JG328258,01/01/2022 12:01:00 AM,008XX W BUENA AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,46.0,3,26,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN

In [103]:
# same result as above using function 'isin()' (don't forget the square brackets)
chicago_crimes[chicago_crimes['Location Description'].isin(['RESIDENCE', 'APARTMENT', 'STREET'])]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13032945,JG212426,10/23/2022 12:00:00 PM,006XX W IRVING PARK RD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,46.0,6,26,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
5,12600669,JF122951,01/24/2022 05:30:00 PM,018XX W GRAND AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,36.0,24,07,1164069.0,1903522.0,2022,07/06/2023 04:46:09 PM,41.890889,-87.672907,"(41.890889291, -87.672907259)"
6,12757467,JF313006,07/10/2022 08:00:00 PM,007XX W 54TH PL,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,16.0,61,05,1172394.0,1868734.0,2022,07/06/2023 04:46:09 PM,41.795248,-87.643360,"(41.7952482, -87.643360273)"
7,12770469,JF328862,07/23/2022 04:00:00 PM,069XX W 64TH PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,True,...,13.0,64,08B,1131307.0,1860969.0,2022,07/06/2023 04:46:09 PM,41.774746,-87.794208,"(41.774745709, -87.794208216)"
8,12776417,JF335627,07/29/2022 03:09:00 AM,052XX N NAGLE AVE,0550,ASSAULT,AGGRAVATED POLICE OFFICER - HANDGUN,STREET,False,False,...,41.0,10,04A,1132572.0,1934567.0,2022,07/06/2023 04:46:09 PM,41.976687,-87.787856,"(41.976687342, -87.787856137)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238654,12678162,JF216753,04/23/2022 03:56:00 AM,047XX S LOOMIS BLVD,041A,BATTERY,AGGRAVATED - HANDGUN,STREET,False,False,...,20.0,61,04B,1167798.0,1873280.0,2022,01/03/2023 03:46:28 PM,41.807823,-87.660083,"(41.807822931, -87.660083294)"
238655,13129089,JG327504,09/27/2022 12:00:00 AM,059XX N HERMITAGE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,False,...,40.0,77,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238658,13130030,JG328516,06/17/2022 12:01:00 AM,004XX S LOTUS AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,29.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238659,13128041,JG326305,12/01/2022 12:00:00 AM,049XX W WEST END AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,...,28.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238661,13129895,JG328258,01/01/2022 12:01:00 AM,008XX W BUENA AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,46.0,3,26,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN

In [104]:
# combination of 'isin()' with AND condition and '<=' operator
chicago_crimes[chicago_crimes['Location Description'].isin(['RESIDENCE', 'APARTMENT', 'STREET']) & (chicago_crimes['Ward'] <= 15.0)]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
7,12770469,JF328862,07/23/2022 04:00:00 PM,069XX W 64TH PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,True,...,13.0,64,08B,1131307.0,1860969.0,2022,07/06/2023 04:46:09 PM,41.774746,-87.794208,"(41.774745709, -87.794208216)"
11,12886511,JF467255,11/07/2022 12:00:00 AM,065XX S MOZART ST,1750,OFFENSE INVOLVING CHILDREN,CHILD ABUSE,RESIDENCE,False,False,...,15.0,66,08B,1158504.0,1861158.0,2022,07/06/2023 04:46:09 PM,41.774753,-87.694502,"(41.774753227, -87.694501757)"
12,12901029,JF484488,11/22/2022 10:01:00 PM,0000X W 114TH PL,143A,WEAPONS VIOLATION,UNLAWFUL POSSESSION - HANDGUN,RESIDENCE,True,False,...,9.0,49,15,1177990.0,1829046.0,2022,07/06/2023 04:46:09 PM,41.686214,-87.624039,"(41.686214418, -87.624039314)"
17,13130214,JG328707,09/01/2022 12:00:00 AM,0000X W DIVISION ST,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,2.0,8,07,NaN,NaN,2022,07/06/2023 04:48:39 PM,NaN,NaN,NaN
20,13130275,JG328904,10/31/2022 10:21:00 PM,012XX N WOLCOTT AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,APARTMENT,False,False,...,1.0,24,11,NaN,NaN,2022,07/06/2023 04:48:39 PM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238616,27250,JF502439,12/13/2022 07:00:00 AM,000XX E 28TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,3.0,35,01A,1177042.0,1886302.0,2022,12/20/2022 03:49:46 PM,41.843353,-87.625786,"(41.843352658, -87.6257856)"
238622,27256,JF508365,12/16/2022 02:55:00 PM,060XX S HARPER AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,5.0,42,01A,1187485.0,1865030.0,2022,12/23/2022 03:48:06 PM,41.784738,-87.588140,"(41.784738437, -87.58813972)"
238627,27262,JF518510,12/21/2022 12:00:00 PM,004XX E 48TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,3.0,38,01A,1179940.0,1873289.0,2022,12/28/2022 03:49:46 PM,41.807578,-87.615550,"(41.807577988, -87.615549695)"
238629,27264,JF519805,12/22/2022 12:09:00 PM,071XX S WOODLAWN AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,5.0,69,01A,1185447.0,1857933.0,2022,06/22/2023 04:45:12 PM,41.765312,-87.595835,"(41.765311868, -87.595834916)"
238644,27290,JF504906,12/29/2022 04:59:00 AM,000XX E MARQUETTE RD,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,6.0,69,01A,1177680.0,1860585.0,2022,01/09/2023 03:46:39 PM,41.772768,-87.624223,"(41.77276846, -87.624222987)"

In [106]:
chicago_crimes[chicago_crimes['Location'].isna()] # select rows where 'Location' IS empty

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13032945,JG212426,10/23/2022 12:00:00 PM,006XX W IRVING PARK RD,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,46.0,6,26,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
1,12713141,JF259485,05/29/2022 12:00:00 AM,014XX S MUSEUM CAMPUS DR,0870,THEFT,POCKET-PICKING,SPORTS ARENA / STADIUM,False,False,...,4.0,33,06,NaN,NaN,2022,06/05/2022 04:48:59 PM,NaN,NaN,NaN
2,13032436,JG211735,04/20/2022 12:01:00 AM,039XX S CALIFORNIA AVE,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,POLICE FACILITY / VEHICLE PARKING LOT,False,False,...,12.0,58,17,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
3,13032916,JG212285,12/14/2022 03:35:00 PM,007XX E 40TH ST,0890,THEFT,FROM BUILDING,SCHOOL - PRIVATE BUILDING,False,False,...,4.0,38,06,NaN,NaN,2022,04/06/2023 05:05:58 PM,NaN,NaN,NaN
4,12871591,JF449106,10/17/2022 05:24:00 PM,022XX N KEELER AVE,0820,THEFT,$500 AND UNDER,RESIDENCE - PORCH / HALLWAY,False,False,...,35.0,20,06,NaN,NaN,2022,10/26/2022 04:52:31 PM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238658,13130030,JG328516,06/17/2022 12:01:00 AM,004XX S LOTUS AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,29.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238659,13128041,JG326305,12/01/2022 12:00:00 AM,049XX W WEST END AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,...,28.0,25,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238660,13128260,JG325445,10/02/2022 04:15:00 PM,082XX S DREXEL AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,8.0,44,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238661,13129895,JG328258,01/01/2022 12:01:00 AM,008XX W BUENA AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,False,...,46.0,3,26,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN
238662,13129286,JG326911,12/22/2022 12:00:00 PM,030XX N SHEFFIELD AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,44.0,6,11,NaN,NaN,2022,07/05/2023 04:48:33 PM,NaN,NaN,NaN

In [107]:
chicago_crimes[chicago_crimes['Location'].notna()] # select rows where 'Location' IS NOT empty

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
5,12600669,JF122951,01/24/2022 05:30:00 PM,018XX W GRAND AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,36.0,24,07,1164069.0,1903522.0,2022,07/06/2023 04:46:09 PM,41.890889,-87.672907,"(41.890889291, -87.672907259)"
6,12757467,JF313006,07/10/2022 08:00:00 PM,007XX W 54TH PL,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,16.0,61,05,1172394.0,1868734.0,2022,07/06/2023 04:46:09 PM,41.795248,-87.643360,"(41.7952482, -87.643360273)"
7,12770469,JF328862,07/23/2022 04:00:00 PM,069XX W 64TH PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,True,...,13.0,64,08B,1131307.0,1860969.0,2022,07/06/2023 04:46:09 PM,41.774746,-87.794208,"(41.774745709, -87.794208216)"
8,12776417,JF335627,07/29/2022 03:09:00 AM,052XX N NAGLE AVE,0550,ASSAULT,AGGRAVATED POLICE OFFICER - HANDGUN,STREET,False,False,...,41.0,10,04A,1132572.0,1934567.0,2022,07/06/2023 04:46:09 PM,41.976687,-87.787856,"(41.976687342, -87.787856137)"
9,12803695,JF367998,08/23/2022 10:29:00 PM,055XX S PRAIRIE AVE,041A,BATTERY,AGGRAVATED - HANDGUN,APARTMENT,True,True,...,20.0,40,04B,1178988.0,1868183.0,2022,07/06/2023 04:46:09 PM,41.793588,-87.619197,"(41.793588428, -87.619196923)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238649,27402,JF177877,05/05/2022 08:42:00 AM,030XX E 92ND ST,0110,HOMICIDE,FIRST DEGREE MURDER,ALLEY,False,False,...,10.0,46,01A,1197914.0,1844540.0,2022,03/30/2023 05:01:17 PM,41.728258,-87.550587,"(41.728258086, -87.550587002)"
238650,27464,JF115197,01/25/2022 07:00:00 AM,035XX N CLARK ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,44.0,6,01A,1168488.0,1923884.0,2022,05/07/2023 04:47:57 PM,41.946669,-87.656088,"(41.946669268, -87.65608802)"
238651,27504,JF257221,05/29/2022 05:41:00 PM,055XX N PARKSIDE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,...,45.0,11,01A,1137530.0,1936472.0,2022,05/19/2023 04:48:43 PM,41.981827,-87.769577,"(41.981826743, -87.769577054)"
238653,12640094,JF171291,03/11/2022 07:30:00 PM,019XX W NORTH AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,32.0,24,07,1162994.0,1910660.0,2022,01/03/2023 03:46:28 PM,41.910499,-87.676655,"(41.910499138, -87.67665453)"
238654,12678162,JF216753,04/23/2022 03:56:00 AM,047XX S LOOMIS BLVD,041A,BATTERY,AGGRAVATED - HANDGUN,STREET,False,False,...,20.0,61,04B,1167798.0,1873280.0,2022,01/03/2023 03:46:28 PM,41.807823,-87.660083,"(41.807822931, -87.660083294)"